name: Update Composer

on:
  workflow_dispatch:
    branches: '**'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git --version
        USER_NAME=$(git log -1 --pretty=format:'%an')
        USER_EMAIL=$(git log -1 --pretty=format:'%ae')
        git config --global user.name "$USER_NAME"
        git config --global user.email "$USER_EMAIL"
        echo "Operating as $USER_NAME <$USER_EMAIL>"
        
    - name: Create update branch
      run: |
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
        VERSION=$(git describe --exact-match)
        a=( ${VERSION//./ } )
        ((a[2]++))
        UPDATE_BRANCH="update/$BRANCH-${a[0]}-${a[1]}-${a[2]}"
        git checkout -b $UPDATE_BRANCH

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress

